Importing of Python libraries

In [208]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt
!pip install skimpy
import skimpy # alternative to pyjanitor

Requirement already satisfied: skimpy in /usr/local/lib/python3.10/dist-packages (0.0.15)
Requirement already satisfied: Pygments<3.0.0,>=2.10.0 in /usr/local/lib/python3.10/dist-packages (from skimpy) (2.18.0)
Requirement already satisfied: click<9.0.0,>=8.1.6 in /usr/local/lib/python3.10/dist-packages (from skimpy) (8.1.7)
Requirement already satisfied: ipykernel<7.0.0,>=6.7.0 in /usr/local/lib/python3.10/dist-packages (from skimpy) (6.29.5)
Requirement already satisfied: numpy<2.0.0,>=1.22.2 in /usr/local/lib/python3.10/dist-packages (from skimpy) (1.26.4)
Requirement already satisfied: pandas<3.0.0,>=2.0.3 in /usr/local/lib/python3.10/dist-packages (from skimpy) (2.2.2)
Requirement already satisfied: polars<0.21,>=0.19 in /usr/local/lib/python3.10/dist-packages (from skimpy) (0.20.31)
Requirement already satisfied: pyarrow<17,>=13 in /usr/local/lib/python3.10/dist-packages (from skimpy) (16.1.0)
Requirement already satisfied: rich<14.0,>=10.9 in /usr/local/lib/python3.10/dist-packages (from skimpy) (13.9.2)
Requirement already satisfied: typeguard==4.2.1 in /usr/local/lib/python3.10/dist-packages (from skimpy) (4.2.1)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.10/dist-packages (from typeguard==4.2.1->skimpy) (4.12.2)
Requirement already satisfied: comm>=0.1.1 in /usr/local/lib/python3.10/dist-packages (from ipykernel<7.0.0,>=6.7.0->skimpy) (0.2.2)
Requirement already satisfied: debugpy>=1.6.5 in /usr/local/lib/python3.10/dist-packages (from ipykernel<7.0.0,>=6.7.0->skimpy) (1.6.6)
Requirement already satisfied: ipython>=7.23.1 in /usr/local/lib/python3.10/dist-packages (from ipykernel<7.0.0,>=6.7.0->skimpy) (7.34.0)
Requirement already satisfied: jupyter-client>=6.1.12 in /usr/local/lib/python3.10/dist-packages (from ipykernel<7.0.0,>=6.7.0->skimpy) (6.1.12)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.10/dist-packages (from ipykernel<7.0.0,>=6.7.0->skimpy) (5.7.2)
Requirement already satisfied: matplotlib-inline>=0.1 in /usr/local/lib/python3.10/dist-packages (from ipykernel<7.0.0,>=6.7.0->skimpy) (0.1.7)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.10/dist-packages (from ipykernel<7.0.0,>=6.7.0->skimpy) (1.6.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from ipykernel<7.0.0,>=6.7.0->skimpy) (24.1)
Requirement already satisfied: psutil in /usr/local/lib/python3.10/dist-packages (from ipykernel<7.0.0,>=6.7.0->skimpy) (5.9.5)
Requirement already satisfied: pyzmq>=24 in /usr/local/lib/python3.10/dist-packages (from ipykernel<7.0.0,>=6.7.0->skimpy) (24.0.1)
Requirement already satisfied: tornado>=6.1 in /usr/local/lib/python3.10/dist-packages (from ipykernel<7.0.0,>=6.7.0->skimpy) (6.3.3)
Requirement already satisfied: traitlets>=5.4.0 in /usr/local/lib/python3.10/dist-packages (from ipykernel<7.0.0,>=6.7.0->skimpy) (5.7.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas<3.0.0,>=2.0.3->skimpy) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas<3.0.0,>=2.0.3->skimpy) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas<3.0.0,>=2.0.3->skimpy) (2024.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich<14.0,>=10.9->skimpy) (3.0.0)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.10/dist-packages (from ipython>=7.23.1->ipykernel<7.0.0,>=6.7.0->skimpy) (71.0.4)
Requirement already satisfied: jedi>=0.16 in /usr/local/lib/python3.10/dist-packages (from ipython>=7.23.1->ipykernel<7.0.0,>=6.7.0->skimpy) (0.19.1)
Requirement already satisfied: decorator in /usr/local/lib/python3.10/dist-packages (from ipython>=7.23.1->ipykernel<7.0.0,>=6.7.0->skimpy) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.10/dist-packages (from ipython>=7.23.1->ipykernel<7.0.0,>=6.7.0->skimpy) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from ipython>=7.23.1->ipykernel<7.0.0,>=6.7.0->skimpy) (3.0.48)
Requirement already satisfied: backcall in /usr/local/lib/python3.10/dist-packages (from ipython>=7.23.1->ipykernel<7.0.0,>=6.7.0->skimpy) (0.2.0)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.10/dist-packages (from ipython>=7.23.1->ipykernel<7.0.0,>=6.7.0->skimpy) (4.9.0)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.10/dist-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel<7.0.0,>=6.7.0->skimpy) (4.3.6)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py>=2.2.0->rich<14.0,>=10.9->skimpy) (0.1.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas<3.0.0,>=2.0.3->skimpy) (1.16.0)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in /usr/local/lib/python3.10/dist-packages (from jedi>=0.16->ipython>=7.23.1->ipykernel<7.0.0,>=6.7.0->skimpy) (0.8.4)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.10/dist-packages (from pexpect>4.3->ipython>=7.23.1->ipykernel<7.0.0,>=6.7.0->skimpy) (0.7.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.10/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=7.23.1->ipykernel<7.0.0,>=6.7.0->skimpy) (0.2.13)

Loading of CSV files

In [209]:
daily_activity = pd.read_csv('dailyActivity_merged copy.csv')
daily_intensities = pd.read_csv('dailyIntensities_merged copy.csv')
hourly_intensities = pd.read_csv('hourlyIntensities_revised.csv')
hourly_calories = pd.read_csv('hourlyCalories_revised.csv')
hourly_steps = pd.read_csv('hourlySteps_revised.csv')
sleep_day = pd.read_csv('sleepDay_revised.csv')
weight_log = pd.read_csv('weightLogInfo_revised.csv')

# Data Cleaning

Seperate 'activity_hour' columns into 'hour' and 'weekday' columns

In [210]:
hourly_calories[['date','hour']] = hourly_calories.ActivityHour.str.split(expand=True)
hourly_steps[['date','hour']] = hourly_steps.ActivityHour.str.split(expand=True)
hourly_intensities[['date','hour']] = hourly_intensities.ActivityHour.str.split(expand=True)
weight_log[['date','hour']] = weight_log.Date.str.split(expand=True)

# Deleting ActivityHour column
hourly_calories.drop(columns = ['ActivityHour'], inplace = True)
hourly_steps.drop(columns = ['ActivityHour'], inplace = True)
hourly_intensities.drop(columns = ['ActivityHour'], inplace = True)
weight_log.drop(columns = ['Date'], inplace = True)
hourly_intensities.head()

# Reordering columns
hourly_calories = hourly_calories[['Id', 'date', 'hour', 'Calories']]
hourly_steps = hourly_steps[['Id', 'date', 'hour', 'StepTotal']]
hourly_intensities = hourly_intensities[['Id', 'date', 'hour', 'TotalIntensity', 'AverageIntensity']]
weight_log = weight_log[['Id', 'date', 'hour', 'WeightKg', 'WeightPounds', 'Fat', 'BMI', 'IsManualReport', 'LogId']]

Verifying columns are of the correct data type

In [211]:
daily_activity['Id'] = daily_activity['Id'].astype(str)
daily_activity['ActivityDate'] = pd.to_datetime(daily_activity['ActivityDate'], format = '%m/%d/%Y')
daily_activity.dtypes

Id                                  object
ActivityDate                datetime64[ns]
TotalSteps                           int64
TotalDistance                      float64
TrackerDistance                    float64
LoggedActivitiesDistance           float64
VeryActiveDistance                 float64
ModeratelyActiveDistance           float64
LightActiveDistance                float64
SedentaryActiveDistance            float64
VeryActiveMinutes                    int64
FairlyActiveMinutes                  int64
LightlyActiveMinutes                 int64
SedentaryMinutes                     int64
Calories                             int64
dtype: object

In [212]:
hourly_intensities['Id'] = hourly_intensities['Id'].astype(str)
# Casting 'date' and 'hour' columns as datetime and time objects
hourly_intensities['date'] = pd.to_datetime(hourly_intensities['date'], format = '%m/%d/%y')
hourly_intensities['hour'] = pd.to_datetime(hourly_intensities['hour'], format = '%H:%M').dt.time
hourly_intensities.dtypes

Id                          object
date                datetime64[ns]
hour                        object
TotalIntensity               int64
AverageIntensity           float64
dtype: object

In [213]:
hourly_calories['Id'] = hourly_calories['Id'].astype(str)
# Casting 'date' and 'hour' columns as datetime and time objects
hourly_calories['date'] = pd.to_datetime(hourly_calories['date'], format = '%m/%d/%y')
hourly_calories['hour'] = pd.to_datetime(hourly_calories['hour'], format = '%H:%M').dt.time
hourly_calories.dtypes

Id                  object
date        datetime64[ns]
hour                object
Calories             int64
dtype: object

In [214]:
hourly_steps['Id'] = hourly_steps['Id'].astype(str)
# Casting 'date' and 'hour' columns as datetime and time objects
hourly_steps['date'] = pd.to_datetime(hourly_steps['date'], format = '%m/%d/%y')
hourly_steps['hour'] = pd.to_datetime(hourly_steps['hour'], format = '%H:%M').dt.time
hourly_steps.dtypes

Id                   object
date         datetime64[ns]
hour                 object
StepTotal             int64
dtype: object

In [215]:
sleep_day['Id'] = sleep_day['Id'].astype(str)
sleep_day['SleepDay'] = pd.to_datetime(sleep_day['SleepDay'], format = '%m/%d/%y %H:%M')
sleep_day.dtypes

Id                            object
SleepDay              datetime64[ns]
TotalSleepRecords              int64
TotalMinutesAsleep             int64
TotalTimeInBed                 int64
dtype: object

In [216]:
weight_log['Id'] = weight_log['Id'].astype(str)
weight_log['LogId'] = weight_log['LogId'].astype(str)
# Casting 'date' and 'hour' columns as datetime and time objects
weight_log['date'] = pd.to_datetime(weight_log['date'], format = '%m/%d/%y')
weight_log['hour'] = pd.to_datetime(weight_log['hour'], format = '%H:%M').dt.time
weight_log.dtypes

Id                        object
date              datetime64[ns]
hour                      object
WeightKg                 float64
WeightPounds             float64
Fat                      float64
BMI                      float64
IsManualReport              bool
LogId                     object
dtype: object

Checking dataframes for null values

In [217]:
print(daily_activity.isnull().values.any())
print(daily_intensities.isnull().values.any())
print(hourly_intensities.isnull().values.any())
print(hourly_calories.isnull().values.any())
print(hourly_steps.isnull().values.any())
print(sleep_day.isnull().values.any())

False
False
False
False
False
False

In [218]:
print(weight_log.isnull().values.any())
null_rows = weight_log[weight_log.isnull().values] # Returning rows with a null value
print(null_rows.to_string())
weight_log = weight_log.drop(columns = ['Fat']) # Dropping 'Fat' columns due to the large number of missing values

True
            Id       date      hour    WeightKg  WeightPounds  Fat        BMI  IsManualReport            LogId
1   1503960366 2016-05-03  23:59:00   52.599998    115.963146  NaN  22.650000            True  1462320000000.0
2   1927972279 2016-04-13  01:08:00  133.500000    294.317120  NaN  47.540001           False  1460510000000.0
3   2873212765 2016-04-21  23:59:00   56.700001    125.002104  NaN  21.450001            True  1461280000000.0
4   2873212765 2016-05-12  23:59:00   57.299999    126.324875  NaN  21.690001            True  1463100000000.0
6   4319703577 2016-05-04  23:59:00   72.300003    159.394222  NaN  27.379999            True  1462410000000.0
7   4558609924 2016-04-18  23:59:00   69.699997    153.662190  NaN  27.250000            True  1461020000000.0
8   4558609924 2016-04-25  23:59:00   70.300003    154.984977  NaN  27.459999            True  1461630000000.0
9   4558609924 2016-05-01  23:59:00   69.900002    154.103125  NaN  27.320000            True  1462150000000.0
10  4558609924 2016-05-02  23:59:00   69.199997    152.559879  NaN  27.040001            True  1462230000000.0
11  4558609924 2016-05-09  23:59:00   69.099998    152.339420  NaN  27.000000            True  1462840000000.0
12  5577150313 2016-04-17  09:17:00   90.699997    199.959265  NaN  28.000000           False  1460880000000.0
13  6962181067 2016-04-12  23:59:00   62.500000    137.788914  NaN  24.389999            True  1460510000000.0
14  6962181067 2016-04-13  23:59:00   62.099998    136.907061  NaN  24.240000            True  1460590000000.0
15  6962181067 2016-04-14  23:59:00   61.700001    136.025217  NaN  24.100000            True  1460680000000.0
16  6962181067 2016-04-15  23:59:00   61.500000    135.584291  NaN  24.000000            True  1460760000000.0
17  6962181067 2016-04-16  23:59:00   62.000000    136.686603  NaN  24.209999            True  1460850000000.0
18  6962181067 2016-04-17  23:59:00   61.400002    135.363832  NaN  23.959999            True  1460940000000.0
19  6962181067 2016-04-18  23:59:00   61.200001    134.922906  NaN  23.889999            True  1461020000000.0
20  6962181067 2016-04-19  23:59:00   61.400002    135.363832  NaN  23.959999            True  1461110000000.0
21  6962181067 2016-04-20  23:59:00   61.700001    136.025217  NaN  24.100000            True  1461200000000.0
22  6962181067 2016-04-21  23:59:00   61.400002    135.363832  NaN  23.959999            True  1461280000000.0
23  6962181067 2016-04-22  23:59:00   61.400002    135.363832  NaN  23.959999            True  1461370000000.0
24  6962181067 2016-04-23  23:59:00   61.500000    135.584291  NaN  24.000000            True  1461460000000.0
25  6962181067 2016-04-24  23:59:00   61.500000    135.584291  NaN  24.000000            True  1461540000000.0
26  6962181067 2016-04-25  23:59:00   61.700001    136.025217  NaN  24.100000            True  1461630000000.0
27  6962181067 2016-04-27  23:59:00   61.200001    134.922906  NaN  23.889999            True  1461800000000.0
28  6962181067 2016-04-28  23:59:00   61.200001    134.922906  NaN  23.889999            True  1461890000000.0
29  6962181067 2016-04-29  23:59:00   61.400002    135.363832  NaN  23.959999            True  1461970000000.0
30  6962181067 2016-04-30  23:59:00   61.000000    134.481980  NaN  23.820000            True  1462060000000.0
31  6962181067 2016-05-01  23:59:00   61.700001    136.025217  NaN  24.100000            True  1462150000000.0
32  6962181067 2016-05-02  23:59:00   61.500000    135.584291  NaN  24.000000            True  1462230000000.0
33  6962181067 2016-05-03  23:59:00   61.000000    134.481980  NaN  23.820000            True  1462320000000.0
34  6962181067 2016-05-04  23:59:00   61.099998    134.702439  NaN  23.850000            True  1462410000000.0
35  6962181067 2016-05-05  23:59:00   61.299999    135.143365  NaN  23.930000            True  1462490000000.0
36  6962181067 2016-05-06  23:59:00   61.500000    135.584291  NaN  24.000000            True  1462580000000.0
37  6962181067 2016-05-07  23:59:00   61.200001    134.922906  NaN  23.889999            True  1462670000000.0
38  6962181067 2016-05-08  23:59:00   61.200001    134.922906  NaN  23.889999            True  1462750000000.0
39  6962181067 2016-05-09  23:59:00   62.400002    137.568455  NaN  24.350000            True  1462840000000.0
40  6962181067 2016-05-10  23:59:00   62.099998    136.907061  NaN  24.240000            True  1462920000000.0
41  6962181067 2016-05-11  23:59:00   61.900002    136.466144  NaN  24.170000            True  1463010000000.0
42  6962181067 2016-05-12  23:59:00   61.900002    136.466144  NaN  24.170000            True  1463100000000.0
43  8877689391 2016-04-12  06:47:00   85.800003    189.156628  NaN  25.680000           False  1460440000000.0
44  8877689391 2016-04-13  06:55:00   84.900002    187.172464  NaN  25.410000           False  1460530000000.0
45  8877689391 2016-04-14  06:48:00   84.500000    186.290612  NaN  25.309999           False  1460620000000.0
46  8877689391 2016-04-16  13:39:00   85.500000    188.495234  NaN  25.590000           False  1460810000000.0
47  8877689391 2016-04-18  06:51:00   85.800003    189.156628  NaN  25.680000           False  1460960000000.0
48  8877689391 2016-04-19  06:39:00   85.300003    188.054316  NaN  25.530001           False  1461050000000.0
49  8877689391 2016-04-20  06:44:00   84.900002    187.172464  NaN  25.410000           False  1461130000000.0
50  8877689391 2016-04-21  06:50:00   84.500000    186.290612  NaN  25.290001           False  1461220000000.0
51  8877689391 2016-04-23  07:22:00   85.500000    188.495234  NaN  25.590000           False  1461400000000.0
52  8877689391 2016-04-24  07:38:00   85.500000    188.495234  NaN  25.590000           False  1461480000000.0
53  8877689391 2016-04-25  06:40:00   85.400002    188.274775  NaN  25.559999           False  1461570000000.0
54  8877689391 2016-04-26  06:50:00   85.099998    187.613382  NaN  25.490000           False  1461650000000.0
55  8877689391 2016-04-27  06:51:00   85.400002    188.274775  NaN  25.559999           False  1461740000000.0
56  8877689391 2016-04-28  06:50:00   85.099998    187.613382  NaN  25.490000           False  1461830000000.0
57  8877689391 2016-04-29  06:49:00   84.900002    187.172464  NaN  25.410000           False  1461910000000.0
58  8877689391 2016-04-30  07:49:00   85.500000    188.495234  NaN  25.590000           False  1462000000000.0
59  8877689391 2016-05-01  08:47:00   85.300003    188.054316  NaN  25.530001           False  1462090000000.0
60  8877689391 2016-05-03  06:49:00   84.900002    187.172464  NaN  25.410000           False  1462260000000.0
61  8877689391 2016-05-04  06:48:00   84.400002    186.070153  NaN  25.260000           False  1462340000000.0
62  8877689391 2016-05-06  06:43:00   85.000000    187.392923  NaN  25.440001           False  1462520000000.0
63  8877689391 2016-05-08  07:35:00   85.400002    188.274775  NaN  25.559999           False  1462690000000.0
64  8877689391 2016-05-09  06:39:00   85.500000    188.495234  NaN  25.610001           False  1462780000000.0
65  8877689391 2016-05-11  06:51:00   85.400002    188.274775  NaN  25.559999           False  1462950000000.0
66  8877689391 2016-05-12  06:42:00   84.000000    185.188300  NaN  25.139999           False  1463040000000.0

Checking dataframes for duplicate rows

*Dataframes contained duplicate rows due to 24 hour time format; fixed in Excel*

In [219]:
print(daily_activity.duplicated().values.any())
print(daily_intensities.duplicated().values.any())
print(hourly_intensities.duplicated().values.any())
print(hourly_calories.duplicated().values.any())
print(hourly_steps.duplicated().values.any())
print(sleep_day.duplicated().values.any())
sleep_day.drop_duplicates(inplace=True)
print(weight_log.duplicated().values.any())

False
False
False
False
False
True
False

Changing column names to the appropriate format

In [220]:
daily_activity = skimpy.clean_columns(daily_activity)
daily_activity.columns
daily_intensities = skimpy.clean_columns(daily_intensities)
daily_intensities.columns
hourly_intensities = skimpy.clean_columns(hourly_intensities)
hourly_intensities.columns
hourly_calories = skimpy.clean_columns(hourly_calories)
hourly_calories.columns
hourly_steps = skimpy.clean_columns(hourly_steps)
hourly_steps.columns
sleep_day = skimpy.clean_columns(sleep_day)
sleep_day.columns
weight_log = skimpy.clean_columns(weight_log)
weight_log.columns

Index(['id', 'date', 'hour', 'weight_kg', 'weight_pounds', 'bmi',
       'is_manual_report', 'log_id'],
      dtype='object')

Creating 'weekday' column in daily_activity and sleep_day dataframes

In [221]:
daily_activity['weekday'] = daily_activity['activity_date'].dt.day_name()
sleep_day['weekday'] = sleep_day['sleep_day'].dt.day_name()

Creating a dataframe that assigns an activity group of either "Low", "Moderate", "Moderately High", "High", or "Very High" based on where the user's total step count is within the quartiles.

In [222]:
id_activity_grouped = daily_activity.groupby('id')['total_steps'].describe()
activity_group = [] # This list will hold the activity groups of each user
for x in id_activity_grouped['mean']:
  if x <= 3789.75:
    activity_group.append('Low')
  elif x > 3789.75 and x <= 7405.50:
    activity_group.append('Moderate')
  elif x > 3789.75 and x <= 7405.50:
    activity_group.append('Moderately High')
  elif x > 7405.50 and x <= 10727.00:
    activity_group.append('High')
  elif x > 10727.00 and x <= 39019.00:
    activity_group.append('Very High')


user_activity = {
    'id': id_activity_grouped.index,
    'activity_group': activity_group
}
user_activity = pd.DataFrame(user_activity)
user_activity.head()

           id activity_group
0  1503960366      Very High
1  1624580081       Moderate
2  1644430081       Moderate
3  1844505072            Low
4  1927972279            Low

Joining dataframes with user_activity table

In [223]:
hourly_intensities.head()

           id       date      hour  total_intensity  average_intensity
0  1503960366 2016-04-12  00:00:00               20           0.333333
1  1503960366 2016-04-12  01:00:00                8           0.133333
2  1503960366 2016-04-12  02:00:00                7           0.116667
3  1503960366 2016-04-12  03:00:00                0           0.000000
4  1503960366 2016-04-12  04:00:00                0           0.000000

In [224]:
daily_activity = pd.merge(daily_activity, user_activity, how='inner', on='id')
sleep_day = pd.merge(sleep_day, user_activity, how='inner', on='id')
weight_log = pd.merge(weight_log, user_activity, how='inner', on='id')
hourly_calories = pd.merge(hourly_calories, user_activity, how='inner', on='id')
hourly_steps = pd.merge(hourly_steps, user_activity, how='inner', on='id')
hourly_intensities = pd.merge(hourly_intensities, user_activity, how='inner', on='id')

In [225]:
hourly_intensities.head()

,id,date,hour,total_intensity,average_intensity,activity_group
0,1503960366,2016-04-12,00:00:00,20,0.333333,Very High
1,1503960366,2016-04-12,01:00:00,8,0.133333,Very High
2,1503960366,2016-04-12,02:00:00,7,0.116667,Very High
3,1503960366,2016-04-12,03:00:00,0,0.000000,Very High
4,1503960366,2016-04-12,04:00:00,0,0.000000,Very High

# Data Analysis

Generating the general statistics on the daily total steps, daily calories, BMI, and time asleep of users.

In [226]:
daily_activity['total_steps'].describe()

count      940.000000
mean      7637.910638
std       5087.150742
min          0.000000
25%       3789.750000
50%       7405.500000
75%      10727.000000
max      36019.000000
Name: total_steps, dtype: float64

In [227]:
daily_activity['calories'].describe()

count     940.000000
mean     2303.609574
std       718.166862
min         0.000000
25%      1828.500000
50%      2134.000000
75%      2793.250000
max      4900.000000
Name: calories, dtype: float64

In [228]:
weight_log['bmi'].describe()

count    67.000000
mean     25.185224
std       3.066963
min      21.450001
25%      23.959999
50%      24.389999
75%      25.559999
max      47.540001
Name: bmi, dtype: float64

In [229]:
sleep_day['total_minutes_asleep'].describe()

count    410.000000
mean     419.173171
std      118.635918
min       58.000000
25%      361.000000
50%      432.500000
75%      490.000000
max      796.000000
Name: total_minutes_asleep, dtype: float64

Generating general statistics based on weekday

In [230]:
daily_activity.groupby('weekday')['total_steps'].describe()

,count,mean,std,min,25%,50%,75%,max
weekday,,,,,,,,
Friday,126.0,7448.230159,4648.038379,0.0,3994.50,7408.0,10240.50,21727.0
Monday,120.0,7780.866667,4717.820371,0.0,4496.50,7625.5,11051.00,20500.0
Saturday,124.0,8152.975806,5944.301289,0.0,4320.50,6946.0,12008.50,29326.0
Sunday,121.0,6933.231405,5644.242419,0.0,2943.00,6083.0,10145.00,36019.0
Thursday,147.0,7405.836735,5007.989124,0.0,3352.00,7860.0,10650.50,21129.0
Tuesday,152.0,8125.006579,4833.811688,0.0,4700.75,8411.0,11334.75,23186.0
Wednesday,150.0,7559.373333,4810.100651,0.0,4041.75,7317.0,10542.50,23629.0

In [231]:
daily_activity.groupby('weekday')['calories'].describe()

,count,mean,std,min,25%,50%,75%,max
weekday,,,,,,,,
Friday,126.0,2331.785714,674.547808,403.0,1843.25,2203.5,2795.5,4044.0
Monday,120.0,2324.208333,634.715471,1248.0,1887.00,2182.0,2767.0,4157.0
Saturday,124.0,2354.967742,802.463442,0.0,1838.50,2127.5,2814.5,4547.0
Sunday,121.0,2263.000000,706.805926,1214.0,1740.00,2063.0,2690.0,4552.0
Thursday,147.0,2199.571429,805.779602,0.0,1700.50,2065.0,2745.5,4900.0
Tuesday,152.0,2356.013158,709.674069,0.0,1896.50,2229.0,2846.0,4092.0
Wednesday,150.0,2302.620000,669.565938,52.0,1841.00,2143.0,2752.0,4079.0

In [232]:
sleep_day.groupby('weekday')['total_minutes_asleep'].describe()

           count        mean         std    min     25%    50%     75%    max
weekday
Friday      57.0  405.421053  113.053708   82.0  355.00  405.0  465.00  658.0
Monday      46.0  419.500000  119.954389   62.0  368.50  434.0  492.75  796.0
Saturday    57.0  419.070175  155.294060   61.0  340.00  426.0  507.00  775.0
Sunday      55.0  452.745455  145.050721   58.0  380.00  481.0  550.50  700.0
Thursday    64.0  401.296875  102.834692   59.0  377.25  423.5  467.25  545.0
Tuesday     65.0  404.538462   96.089326  103.0  342.00  417.0  465.00  750.0
Wednesday   66.0  434.681818   89.990454  152.0  392.00  444.5  477.00  658.0

# Exporting Files

In [234]:
'''
from google.colab import drive
drive.mount('drive')

# Exporting files to Google Drive in prepartion for Tableau
daily_activity.to_csv('daily_activity_final.csv', index=False)
!cp daily_activity_final.csv "drive/My Drive/"

sleep_day.to_csv('sleep_day_final.csv', index=False)
!cp sleep_day_final.csv "drive/My Drive/"

weight_log.to_csv('weight_log_final.csv', index=False)
!cp weight_log_final.csv "drive/My Drive/"

hourly_calories.to_csv('hourly_calories_final.csv', index=False)
!cp hourly_calories_final.csv "drive/My Drive/"

hourly_steps.to_csv('hourly_steps_final.csv', index=False)
!cp hourly_steps_final.csv "drive/My Drive/"

hourly_intensities.to_csv('hourly_intensities_final.csv', index=False)
!cp hourly_intensities_final.csv "drive/My Drive/"
'''

'\nfrom google.colab import drive\ndrive.mount(\'drive\')\n\n# Exporting files to Google Drive in prepartion for Tableau\ndaily_activity.to_csv(\'daily_activity_final.csv\', index=False)\n!cp daily_activity_final.csv "drive/My Drive/"\n\nsleep_day.to_csv(\'sleep_day_final.csv\', index=False)\n!cp sleep_day_final.csv "drive/My Drive/"\n\nweight_log.to_csv(\'weight_log_final.csv\', index=False)\n!cp weight_log_final.csv "drive/My Drive/"\n\nhourly_calories.to_csv(\'hourly_calories_final.csv\', index=False)\n!cp hourly_calories_final.csv "drive/My Drive/"\n\nhourly_steps.to_csv(\'hourly_steps_final.csv\', index=False)\n!cp hourly_steps_final.csv "drive/My Drive/"\n\nhourly_intensities.to_csv(\'hourly_intensities_final.csv\', index=False)\n!cp hourly_intensities_final.csv "drive/My Drive/"\n'